/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
      extend: {
          "colors": {
              "on-secondary-fixed-variant": "#23501e",
              "error-container": "#ffdad6",
              "on-tertiary-fixed": "#111c2c",
              "surface-container-highest": "#dfe3e7",
              "on-primary": "#ffffff",
              "secondary": "#3b6934",
              "on-tertiary": "#ffffff",
              "tertiary-fixed": "#d8e3fa",
              "tertiary-fixed-dim": "#bcc7dd",
              "outline": "#72777f",
              "primary-fixed-dim": "#a2caf7",
              "on-primary-fixed-variant": "#1d496f",
              "on-secondary": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "tertiary": "#1a2536",
              "secondary-fixed": "#bcf0ae",
              "on-surface": "#171c1f",
              "inverse-primary": "#a2caf7",
              "secondary-fixed-dim": "#a1d494",
              "inverse-surface": "#2c3134",
              "surface-container-high": "#e4e9ed",
              "error": "#ba1a1a",
              "surface-bright": "#f6fafe",
              "on-tertiary-fixed-variant": "#3c475a",
              "surface-variant": "#dfe3e7",
              "on-tertiary-container": "#9aa5bb",
              "on-secondary-container": "#3f6d38",
              "surface-container": "#eaeef2",
              "surface-container-low": "#f0f4f8",
              "on-error-container": "#93000a",
              "on-error": "#ffffff",
              "on-surface-variant": "#42474e",
              "on-background": "#171c1f",
              "tertiary-container": "#303b4d",
              "on-primary-fixed": "#001d34",
              "surface-dim": "#d6dade",
              "on-primary-container": "#80a8d3",
              "primary": "#002743",
              "primary-fixed": "#cfe5ff",
              "background": "#f6fafe",
              "surface-tint": "#386188",
              "inverse-on-surface": "#edf1f5",
              "outline-variant": "#c2c7cf",
              "primary-container": "#0a3d62",
              "surface": "#f6fafe",
              "secondary-container": "#b9eeab",
              "on-secondary-fixed": "#002201"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          "fontFamily": {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
          }
      },
  },
  plugins: [],
};
